#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    PathyApp-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^pathyapp\.app\.local$`)
      
      service: "PathyApp-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "PathyApp-redirectHttps"
    PathyApp-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^pathyapp\.app\.local$`)
      
      service: "PathyApp-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "PathyApp-redirectHttps"
    PathyApp-web-5173-http:
      entrypoints:
        - http-5172
      rule: HostRegexp(`^pathyapp\.app\.local$`)
      
      service: "PathyApp-web-5173"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "PathyApp-redirectHttps"
    PathyApp-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^pathyapp\.app\.local$`)
      
      service: "PathyApp-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "PathyApp-redirectHttps"
    
    
    
    
    PathyApp-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^pathyapp\.app\.local$`)
      
      service: "PathyApp-web-80"
      ruleSyntax: v3
      
      tls: true
      
    PathyApp-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^pathyapp\.app\.local$`)
      
      service: "PathyApp-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    PathyApp-web-5173-https:
      entrypoints:
        - http-5173
      rule: HostRegexp(`^pathyapp\.app\.local$`)
      
      service: "PathyApp-web-5173"
      ruleSyntax: v3
      
      tls: true
      
    
    PathyApp-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^pathyapp\.app\.local$`)
      
      service: "PathyApp-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    PathyApp-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    PathyApp-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-PathyApp-web:80
        
    PathyApp-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-PathyApp-web:8025
        
    PathyApp-web-5173:
      loadbalancer:
        servers:
          - url: http://ddev-PathyApp-web:5173
        
    
    
    
    PathyApp-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-PathyApp-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/PathyApp.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/PathyApp.key